* Tools to aid in reverse engineering of software for the classic AmigaOS

This repository will contain tools I'll be writing to convert certain
loadable file formats into the form that they would be loaded into the
memory of the computer by the operating system itself.


** UnUhunker

The first functional tool is ~UnHunker~ to convert "Hunk" format
executables the way the AmigaOS would do. This allows creating a
statically addressed memory dump segment to be loaded into Ghidra or
another reverse engineering tool for further processing.

Currently it handles HUNK_CODE and HUNK_RELOC32 hunks to produce a
statically addressed monolith. Any hunks to be loaded to chip RAM will
be addressed below 0x100000, other hunks starting from that same 1 MB
boundary. The base address to load the dump is appended to the file
name while the entry point should in most cases stay at 0x100000.

This tool is extended as files with currently "unknown" hunks are
acquired for reverse engineering.

I'm aware that this could be made as a plugin for Ghidra, but
maintaining it to keep it up-to-date with Ghidra would be too much of
a chore for me.


** ADF-tool

This tool will be initially created to extract files and raw blocks
out of /Amiga Disk File/ images. Initially the target will be to be
compatible with disk images that have a partial OFS file system with
custom blocks of data. This has been seen on some floppies of games
that start through the operating system but subsequently load the game
data with a custom trackloader.

The current status of this tool is slow development. Once the reading
part is done, it may be expanded to writing these disk files as well,
most likely with the added benefit of not corrupting any custom
blocks.
